stages:
  - deploy

build-job:
  stage: deploy
  image: docker:24.0
  services:
    - docker:24.0-dind
  tags:
      - home-server
  script:
    - echo "TEST 2"
    - docker run -d --name zaza registry.gitlab.com/zeroking783/zazatappo-vacanzi
    - docker ps -a

