stages:
  - build
  - deploy

build-job:
  stage: build
  image: docker:24.0
  services:
    - docker:24.0-dind
  tags:
    - home-server
  before_script:
    - echo "LOGIN GITLAB REGISTRY"
    - echo "$GITLAB_TOKEN" | docker login registry.gitlab.com -u zeroking783 --password-stdin
  script:
    - echo "BUILD JOB"  
    - docker build -t registry.gitlab.com/zeroking783/zazatappo-vacanzi:latest src/
    - docker push registry.gitlab.com/zeroking783/zazatappo-vacanzi:latest

deploy-job:
  stage: deploy
  image: docker:24.0
  services:
    - docker:24.0-dind
  tags:
      - home-server
  script:
    - echo "DEPLOY zaza"
    # - docker-compose pull 
    # - if ! docker ps -a --format '{{.Names}}' | grep -qE '^(kafka|zookeeper)$'; then echo "KAFKA и ZOOKEEPER НЕ НАЙДЕНЫ, ПЕРЕЗАПУСКАЮ ВСЕ СЕРВИСЫ"; docker-compose up -d; else echo "ПЕРЕЗАПУСКАЮ ТОЛЬКО ZAZA-PARSER"; docker-compose up -d zaza-parser; fi
    - docker pull registry.gitlab.com/zeroking783/zazatappo-vacanzi:latest
    - |
      while docker exec zaza ls /tmp | grep -q zaza; do
        echo "ПРОИСХОДИТ ПАРСИНГ, ЖДЕМ"
        sleep 10
      done
    - echo "ЗАДАЧА ЗАВЕРШЕНА, ДЕПЛОИМ"
    - |
      if docker ps -a --filter "name=zaza" --format '{{.Names}}' | grep zaza; then
        echo "DELETE ZAZA CONTAINER"
        docker rm -f zaza;
      fi
    - docker run -d --name zaza --restart unless-stopped -e VAULT_TOKEN=$VAULT_TOKEN --shm-size="2g" -p 8000:8000 registry.gitlab.com/zeroking783/zazatappo-vacanzi:latest

