stages:
  - deploy

build-job:
  stage: deploy
  image: docker:24.0
  services:
    - docker:24.0-dind
  tags:
      - home-server
  script:
    - echo "DEPLOY zaza"
    - |
      if docker ps -a --filter "name=zaza" --format '{{.Names}}' | grep zaza; then
        echo "DELETE zaza CONTAINER"
        docker rm -f zaza;
      fi
    - docker run -d --name zaza --shm-size="2g" -e VAULT_TOKEN=$VAULT_TOKEN registry.gitlab.com/zeroking783/zazatappo-vacanzi:latest
    - docker ps -a

