stages:
  - deploy

build-job:
  stage: deploy
  image: docker:24.0
  services:
    - docker:24.0-dind
  tags:
      - home-server
  script:
    - echo "DEPLOY zaza"
    # - |
    #   if docker images --filter "reference=registry.gitlab.com/zeroking783/zazatappo-vacanzi" | grep zazatappo-vacanzi; then
    #     echo "DELETE ZAZA IMAGES"
    - docker pull registry.gitlab.com/zeroking783/zazatappo-vacanzi:latest
    - |
      if docker ps -a --filter "name=zaza" --format '{{.Names}}' | grep zaza; then
        echo "DELETE ZAZA CONTAINER"
        docker rm -f zaza;
      fi
    - docker run -d --name zaza -e VAULT_TOKEN=$VAULT_TOKEN --shm-size="2g" registry.gitlab.com/zeroking783/zazatappo-vacanzi:latest
    - docker ps -a

