stages:
  - build
  - deploy

build-job:
  stage: build
  image: docker:24.0
  services:
    - docker:24.0-dind
  tags:
    - home-server
  before_script:
    - echo "LOGIN GITLAB REGISTRY"
    - echo "$GITLAB_TOKEN" | docker login registry.gitlab.com -u zeroking783 --password-stdin
  script:
    - echo "BUILD JOB"
    - docker build -t registry.gitlab.com/zeroking783/zazatappo-vacanzi:latest src/
    - docker push registry.gitlab.com/zeroking783/zazatappo-vacanzi:latest
    - docker images 

deploy-job:
  stage: deploy
  image: docker:24.0
  services:
    - docker:24.0-dind
  tags:
      - home-server
  script:
    - echo "DEPLOY zaza"
    - docker pull registry.gitlab.com/zeroking783/zazatappo-vacanzi:latest
    - |
      if docker ps -a --filter "name=zaza" --format '{{.Names}}' | grep zaza; then
        echo "DELETE ZAZA CONTAINER"
        docker rm -f zaza;
      fi
    - docker run -d --name zaza -e VAULT_TOKEN=$VAULT_TOKEN --shm-size="2g" registry.gitlab.com/zeroking783/zazatappo-vacanzi:latest
    - docker ps -a

